apiVersion: apps/v1
kind: Deployment
metadata:
  name: godeploy
  labels:
    app: godeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: godeploy
  template:
    metadata:
      labels:
        app: godeploy
    spec:
      containers:
      - name: godeploy
        image: dmitrydorofeev/godeploy:6a90f947
        ports:
        - containerPort: 8080