apiVersion: apps/v1
kind: Deployment
metadata:
  name: godeploy
  labels:
    app: godeploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: godeploy
  template:
    metadata:
      labels:
        app: godeploy
    spec:
      containers:
      - name: app
        image: dmitrydorofeev/godeploy:2702f7c2
        ports:
        - containerPort: 8080