---
- name: "Update systemd unit"
  become: yes
  hosts: web
  tasks:
    - name: "Provide latest unit file"
      copy:
        src: files/api.service
        dest: /etc/systemd/system/api.service
    - name: "Systemctl daemon reload"
      command: systemctl daemon-reload
- name: "Install docker"
  become: yes
  hosts: all
  roles:
    - role: geerlingguy.docker
- name: "Install nginx"
  become: yes
  hosts: web
  tasks:
    - name: "Install nginx package"
      apt:
        name: nginx
        state: present
    - name: "Copy nginx config"
      copy:
        src: files/frontend.conf
        dest: /etc/nginx/sited-enabled/
    - name: "Reload nginx"
      command: "nginx -s reload"
