name: Docker Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build Docker image
      run: docker build -t dmitrydorofeev/godeploy:${GITHUB_SHA::8} .
    - name: Push the image
      run: docker push dmitrydorofeev/godeploy:${GITHUB_SHA::8}
